### ISSUE TITLE
Support sass variables

### ISSUE THREAD

**Issue by fogrew** [lutien/postcss-extract-value#9]
I would like to be able to write not only on styles sss4 but using preprocessors like sass, less or stylus syntax.

Input:

``` css
.foo {
     width: 100px;
     color: #000;
     margin: 10px;
}
.bar {
     color: #000;
     margin: 15px;
}
```

Output scss:

``` scss
$width-1: 100px;
$color-1: #000;
$margin-1: 10px;
$margin-2: 15px;

.foo {
    width: $width-1;
    color: $color-1;
    margin: $margin-1;
}
.bar {
    color: $color-1;
    margin: $margin-2;
}
```

or less:

``` less
@width-1: 100px;
@color-1: #000;
@margin-1: 10px;
@margin-2: 15px;

.foo {
    width: @width-1;
    color: @color-1;
    margin: @margin-1;
}
.bar {
    color: @color-1;
    margin: @margin-2;
}
```
